server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: 123321
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
          max-wait: 5000ms
        shutdown-timeout: 100ms
  jackson:
    default-property-inclusion: non_null # JSON序列化时忽略非空字段
    encoding: UTF-8
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 实体扫描包
logging:
  level:
    com.hmdp: debug
